// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AuthCookie.Models;

public partial class Cat
{
    [Key]
    public int Id { get; set; }

    public string Name { get; set; }
}