// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ImportExport.Models;

public partial class VwCusMvRent
{
    public string FullName { get; set; }

    public string Address { get; set; }

    public string Title { get; set; }

    public string Salutation { get; set; }

    public int RentId { get; set; }
}